### ISSUE TITLE
boolean field in where() condition

### ISSUE THREAD

**Issue by kekla** [Dynamoid/Dynamoid#135] opened 2017-03-24 09:15 UTC
In lib/dynamoid/persistence.rb line 317:
`!value.nil? ? value.to_s[0] : nil`
If I save a boolean field as true or false, it will be saved as string 't' or 'f'.
`.where(:some_boolean_field => true)` won't get correct results, I have to change to  `.where(:some_boolean_field => 't')`.
Do you think it's a good idea to use true/false instead?

**Comment by pboling** [comment] 2017-03-25 12:09
That kind of translation can be done in the adapter (that's how Rails / ActiveRecord does it).
We can't change the way the data is stored at this point as it would break compatibility with old data.  For now you will have to use `t` or `f` in the query.  We should look into translating `true` and `false` in the adapter.

Leaving this open for that.

**Comment by pboling** [comment] 2017-03-27 10:10
I have implemented this feature in release 1.3.1 just now.  :integer, :string, and :boolean fields are now run through the same dump process that happens when values are written to Dynamo.

Result: you can query like `where(admin: true)` now.

**Comment by baloran** [comment] 2017-12-08 17:14
Hey, not working for me :/ I have in my model a field of boolean type. And in dynamodb a boolean type too. And I can't make query condition on it.

**Comment by pboling** [comment] 2017-12-08 19:19
@andrykonchin @richardhsu Have any idea about this?  Perhaps we had a regression, or perhaps my implementation was broken, and we need better specs.

**Comment by baloran** [comment] 2017-12-09 13:18
If you can explain where look to find debug, I can try to look :)

**Comment by richardhsu** [comment] 2017-12-10 18:37
Sorry didn't have time to look at this until now. @baloran what version of Dynamoid gem are you using? In our current version I added this to our `spec/criteria/chain.rb` and tests pass:

```
  describe 'Boolean support' do
    let(:model) {
      Class.new do
        include Dynamoid::Document
        table name: :user, key: :name
        field :admin, :boolean
      end
    }

    it 'supports filter boolean field' do
      user1 = model.create(name: 'Bob', admin: true)
      user2 = model.create(name: 'Gene', admin: false)
      user3 = model.create(name: 'Tina', admin: false)
      user4 = model.create(name: 'Louise', admin: true)
      user5 = model.create(name: 'Teddy', admin: 't')
      user6 = model.create(name: 'Frond', admin: 'f')


      expect(model.where(admin: true).all).to contain_exactly(user1, user4, user5)
      expect(model.where(admin: 't').all).to contain_exactly(user1, user4, user5)
    end
  end
```

```
bundle exec rspec spec/dynamoid/criteria/chain_spec.rb:330
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
Run options: include {:locations=>{"./spec/dynamoid/criteria/chain_spec.rb"=>[330]}}

Randomized with seed 4973

Dynamoid::Criteria::Chain
  Boolean support
    supports filter boolean field

Finished in 0.54755 seconds (files took 1.69 seconds to load)
1 example, 0 failures

Randomized with seed 4973
```

Can you also show what the error gives since you're saying you can't make the query, since I'd expect instead you'd get bad results if it weren't translating correctly.

**Comment by baloran** [comment] 2017-12-11 09:27
Hey @richardhsu, my version is 1.3.1. I don't have any warning or error message.  It's like my field in where is ignored.

**Comment by baloran** [comment] 2017-12-11 09:35
Ok I have an advancement. I have upgraded the gem to 1.3.4. But the boolean is transformed in "f" for false and "t" for true. But I think I remember it's normal operation.

**Comment by richardhsu** [comment] 2017-12-11 09:39
Yes, @baloran, this is the normal operation of `true => 't'` and `false => 'f'`:

This is the `dump_field` method for a boolean in `persistence.rb` for reference.
```
            when :boolean
              !value.nil? ? value.to_s[0] : nil
```

**Comment by baloran** [comment] 2017-12-11 09:40
And you think is a way to have real boolean ?

**Comment by richardhsu** [comment] 2017-12-11 09:46
You mean to have a real boolean value in DynamoDB's storage?
In the Ruby model, Dynamoid will hold the value as a real boolean though.

At least for backward compatibility for how it was originally implemented, this is the way we are currently handling it. You're also welcome to open a pull request to handle the case too if this is an issue for you :) I'm not sure when we'll be able to get to such a change.

@andrykonchin  @pboling Maybe we need to discuss figuring out how we'll want to transition to handle Booleans in the correct form. Either a breaking change or have backward compatibility?
Since DynamoDB stores Boolean types as a Number with value of 0 or 1.

**Comment by baloran** [comment] 2017-12-11 09:51
Yes in my dynamodb document is a Boolean with true or false.

I have imagined a conf with choice of boolean instead of string. There is something smooth for transition and do not force people to use boolean. 

Something possible ?

**Comment by andrykonchin** [comment] 2017-12-11 09:53
DynamoDB supports boolean type natively [(documentation)](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html)
> A Boolean type attribute can store either true or false.

So it makes sense to support it in DynamoId too.

Not sure if we can make breaking change, but it's easy enough to add some configuration (on the document field level) to keep old behaviour, e.g.

```ruby
field :activated, :boolean, store_as_string: true
```

@richardhsu @pboling what do you think?

**Comment by richardhsu** [comment] 2017-12-11 23:42
Ah yes, sorry my bad, read the incorrect document for Boolean type as Number. I was reading the Java documentation.

That sounds good. I don't work on any projects that use the boolean flag so I don't really have a preference for how the configuration should be done.

**Comment by pboling** [comment] 2017-12-12 03:20
@andrykonchin that would be great!

**Comment by andrykonchin** [comment] 2017-12-12 09:41
Will work on it soon

**Comment by pboling** [comment] 2017-12-12 18:49
Will re-close when #213 is merged.

**Comment by andrykonchin** [comment] 2017-12-12 20:02
@baloran Done. Check `master`

**Closed by andrykonchin** 2017-12-12 20:02 UTC
Labels: enhancement

**Comment by baloran** [comment] 2017-12-14 09:03
Thanks guys ! If you want to talk about dynamoid and the roadmap I can be here ! I use dynamoid in production for a big product with multiple use case of dynamodb. Thanks !

**Comment by pboling** [comment] 2017-12-15 03:14
@baloran I have been the primary maintainer and I only use a tiny fraction of the gems functionality, so it would be good to get your input on things.  Can I add you to the organization as a contributor?  We really need more feedback on releases / development.
