### ISSUE TITLE
`create` does behave like `new.save`

### ISSUE THREAD

**Issue by cabello** [Dynamoid/dynamoid#325] opened 2019-01-11 16:32 UTC
Hi 👋 

Given the following model:

```ruby
class Post
  include Dynamoid::Document

  field :title, :string
  field :body, :string
end
```

If one runs `Post.create(title: 'Some draft of article')` they get back:

```ruby
ArgumentError:
  missing keywords: body
```

If one runs `Post.new(title: 'Some draft of article').save` the record is persisted and the body is nil.

I find the behaviour of `create` unexpected, I was expecting the exact same behaviour of `new` followed by `save`.

Thank you.

**Comment by andrykonchin** [comment] 2019-01-12 13:44
Could you please specify the Dynamoid version?

Actually I can't reproduce the issue on the current master (and it equals the last minor release)

**Comment by andrykonchin** [comment] 2019-03-06 20:58
Since it’s been two months, I hope things are working well for you now.

I’ll close the issue until we can confirm it’s still happening. I’m happy to continue further discussion whenever needed.

**Closed by andrykonchin** 2019-03-06 20:58 UTC

**Comment by cabello** [comment] 2019-03-06 21:36
Oh, I can try to reproduce it, I completely missed your request for a version for some reason.
