### ISSUE TITLE
Unable to add to Gemfile

### ISSUE THREAD

**Issue by bramu** [Dynamoid/dynamoid#378] opened 2019-08-26 01:18 UTC
As soon as I am adding the dynamoid I am getting the below error. Unable to see what is the issue. Could you please help me with this?

$ rails c
/Users/ramu/.rvm/gems/ruby-2.4.1/gems/aws-sdk-dynamodb-1.16.0/lib/aws-sdk-dynamodb/client_api.rb:1110:in `block in <module:ClientApi>': undefined method `endpoint_operation=' for #<Seahorse::Model::Api> (NoMethodError)
	from /Users/ramu/.rvm/gems/ruby-2.4.1/gems/aws-sdk-dynamodb-1.16.0/lib/aws-sdk-dynamodb/client_api.rb:1094:in `tap'
	from /Users/ramu/.rvm/gems/ruby-2.4.1/gems/aws-sdk-dynamodb-1.16.0/lib/aws-sdk-dynamodb/client_api.rb:1094:in `<module:ClientApi>'
	from /Users/ramu/.rvm/gems/ruby-2.4.1/gems/aws-sdk-dynamodb-1.16.0/lib/aws-sdk-dynamodb/client_api.rb:10:in `<module:DynamoDB>'

**Comment by andrykonchin** [comment] 2019-08-26 07:53
Could you provide sample project to reproduce the issue or more info about it - full backtrace of the exception and a version of Dynamoid?

**Comment by andrykonchin** [comment] 2019-10-14 18:44
Since it’s been two months, I hope things are working well for you now. I’ll close the issue until we can confirm it’s still happening. I’m happy to continue further discussion whenever needed

**Closed by andrykonchin** 2019-10-14 18:44 UTC
