### ISSUE TITLE
how do I perform a sort on the range key?

### ISSUE THREAD

**Issue by rhuang** [Dynamoid/dynamoid#435] opened 2020-05-02 07:11 UTC
I want to run something like:

`Messages.where(hash_key, 'timestamp.lt': 1234567890)`, where the first param is the hash key and the second param is the range key (timestamp). I'm not sure if this is possible from the documentation. And I have a GSI on the hash key and `timestamp`. My use case is that I want to run this query, and also paginate on it, so potentially something like:

```
message_criteria = Messages.where(hash_key, 'timestamp.lt': 1234567890).record_limit(page_size).start(last_message)
```

**Comment by andrykonchin** [comment] 2020-05-02 10:32
Well. Regarding the issue with `where`' conditions. It can look like this:

```ruby
scope = Message.where(id: 'some-value', 'timestamp.lt': Time.now)
```

where `id` is a name of the hash key attribute and `timestamp` is declared as a `datetime` field in the model class. Only if `timestamp` is declared as an `integer`/`number` field the integer value `1234567890` should be used in a condition.

The pagination is used correctly. It's a combination of `record_limit`/`start` or `scan_limit`/`start` methods.

> And I have a GSI on the hash key and timestamp

Not sure if understood you correctly. If `hash_key` attribute isn't a hash key of a table but instead a hash key in some GSI it's completely OK. The efficient `Query` operation will be used but this GSI should be declared in the mode l class to let Dynamoid know its schema.

Please let me know if you have any questions.

**Comment by rhuang** [comment] 2020-05-19 01:41
Hi, sorry for the delay, just saw your reply.

Using `.where` directly doesn't work:

```
irb(main):008:0> User.where(type: 'Client', 'created_at.gt': (DateTime.now - 1.hour).to_i).first
Traceback (most recent call last):
        2: from (irb):8
        1: from (irb):8:in `first'
Aws::DynamoDB::Errors::ValidationException (QueryFilter can only contain non-primary key attributes: Primary key attribute: type)
```

But using the legacy `find_by_secondary_index` works:

```
      User.find_all_by_secondary_index(
        { type: type },
        range: { 'created_at.gte': created_at },
        scan_index_forward: false
      )
```

I have the GSI defined in the model:

`  global_secondary_index name: 'INDEX_FOR_TYPE_CREATED_AT', hash_key: :type, range_key: :created_at, projected_attributes: :all, read_capacity: 3, write_capacity: 3`

**Comment by andrykonchin** [comment] 2020-05-19 10:08
Can you provide a model class definition to reproduce the issue? It looks as a bug in the index selection in `where` method.

**Comment by rhuang** [comment] 2020-05-19 14:35
```
class User
  include Dynamoid::Document

  table name: :USERS, read_capacity: 3, write_capacity: 3

  field :name
  field :first_name
  field :last_name
  field :email
  field :type
  field :created_at, :number # auto populated by Dynamoid
  # more fields...

  global_secondary_index name: 'INDEX_FOR_EMAIL', hash_key: :email, projected_attributes: :all, read_capacity: 3, write_capacity: 3
  global_secondary_index name: 'INDEX_FOR_TYPE_CREATED_AT', hash_key: :type, range_key: :created_at, projected_attributes: :all, read_capacity: 3, write_capacity: 3
  ...
end
```

Primary partition key | id (String)
-- | --

<img width="843" alt="Screen Shot 2020-05-19 at 7 30 44 AM" src="https://user-images.githubusercontent.com/1022385/82339234-ac23cb00-99a2-11ea-8c24-d7839b0eb298.png">

I also noticed, if I didn't explicitly define the `created_at` field, then then I get this error when using the same `where` method: `Aws::DynamoDB::Errors::ValidationException (One or more parameter values were invalid: ComparisonOperator GT is not valid for NULL AttributeValue type)`

The reason I use `type` as part of the index is because I have classes that inherit from `User`, like `Client < User`, and I'm trying to query for `Client` items.

**Comment by andrykonchin** [comment] 2020-05-20 21:04
Yes, it's definitely a bug when STI field `type` is used as a hash key in GSI. Good catch 👍. It will be fixed soon.

> I also noticed, if I didn't explicitly define the created_at field, then then I get this error when using the same where method...

Unfortunately I cannot reproduce the issue with declaring `User` class without explicit `created_at` field. Could you elaborate on it?

**Comment by andrykonchin** [comment] 2020-06-21 11:56
Fixed in https://github.com/Dynamoid/dynamoid/pull/453

**Closed** 2020-06-21 13:16 UTC
