### ISSUE TITLE
Updating an attribute that is a key of a GSI to `nil` (3.9.0)

### ISSUE THREAD

**Issue by zak-raw** [Dynamoid/dynamoid#679] opened 2023-08-10 06:55 UTC
Since `3.9.0`, An error `Aws::DynamoDB::Errors::ValidationException: Invalid attribute value type` is raised when trying to update an attribute that is a key of a GSI to `nil` via `save!`, `update_attributes!`, etc.
This was possible until `3.8.0`.

Also, it seems a configuration `store_attribute_with_nil_value: false` don't work.

```ruby
Dynamoid.configure do |config|
  config.store_attribute_with_nil_value = false
end

class Hoge
  include Dynamoid::Document

  field :foo_id
  
  global_secondary_index(
    hash_key: :foo_id,
    projected_attributes: :all,
  )
end

hoge = Hoge.new(foo_id: 'bar').save!
hoge.foo_id = nil
hoge.save!
# 'Aws::DynamoDB::Errors::ValidationException: Invalid attribute value type' is raised.
```

**Comment by nbulaj** [comment] 2023-08-11 09:24
Just faced the same issue. Not sure if it's AWS or Dynamoid

![image](https://github.com/Dynamoid/dynamoid/assets/1443426/60ffc22f-d279-4e42-9773-d12de42ab129)

**Comment by andrykonchin** [comment] 2023-08-20 20:32
Thank you for the bug report. I fixed the issue in https://github.com/Dynamoid/dynamoid/pull/681. 

Not sure that it makes sense to prepare a patch-level release now because there is already one merged PR with refactoring and new feature (https://github.com/Dynamoid/dynamoid/pull/655).

**Closed** 2023-08-20 20:49 UTC

**Comment by yoshizaki-aill** [comment] 2023-08-21 03:00
@andrykonchin Thank you for your prompt response. 🙇 
I checked the diff and I think the issue is resolved.
I will update Gemfile and test our Rails application when `3.9.1` is released.

**Comment by zak-raw** [comment] 2023-08-21 03:01
@andrykonchin Thank you for your prompt response. 🙇
I checked the diff and I think the issue is resolved.
I will update Gemfile and test our Rails application when 3.9.1 is released.
